# Generated by Django 4.2.3 on 2023-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('content', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('postType', models.CharField(blank=True, choices=[('PR', 'Person'), ('PL', 'Place')], default=None, max_length=75, null=True)),
            ],
        ),
    ]
