# Generated by Django 4.2.3 on 2023-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='postType',
            field=models.CharField(blank=True, choices=[('PR', 'Person'), ('PL', 'Place'), ('MD', 'Media')], default=None, max_length=75, null=True),
        ),
    ]
