# Generated by Django 4.2.3 on 2023-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_publish_alter_article_thumnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publishDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),

        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),

        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
