# Generated by Django 4.2.3 on 2023-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_publishdate_alter_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alpha3',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
