# Generated by Django 4.2.3 on 2023-07-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_alpha3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
