# Generated by Django 4.2.3 on 2023-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_thumnail_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postType',
            field=models.CharField(blank=True, choices=[('person', 'Person'), ('place', 'Place'), ('media', 'Media')], default=None, max_length=75, null=True),
        ),
    ]
