# Generated by Django 4.2.3 on 2023-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contentEsp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
