# Generated by Django 4.2.3 on 2023-08-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pinned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
