# Generated by Django 4.2.3 on 2023-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postType',
            field=models.CharField(blank=True, choices=[('person', 'Person'), ('place', 'Place'), ('media', 'Media'), ('resource', 'Resource'), ('food', 'Food')], default=None, max_length=75, null=True),
        ),
    ]
