# Generated by Django 4.2.3 on 2023-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishDate',
            field=models.DateField(blank=True, default=None),
        ),
    ]
