# Generated by Django 4.2.3 on 2023-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
