# Generated by Django 4.2.3 on 2023-09-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(editable=False, max_length=50)),
                ('lastName', models.CharField(blank=True, editable=False, max_length=50)),
                ('email', models.EmailField(editable=False, max_length=75)),
                ('subscribeTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
