# Generated by Django 4.2.3 on 2023-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_alter_subscriber_email_alter_subscriber_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='recaptchaScore',
            field=models.FloatField(default=0.9, editable=False),
            preserve_default=False,
        ),
    ]
