# Generated by Django 4.2.3 on 2023-09-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_subscriber_recaptchascore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='recaptchaScore',
        ),
    ]
