# Generated by Django 4.2.3 on 2023-10-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0004_remove_subscriber_recaptchascore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='lastName',
        ),
    ]
