# Generated by Django 4.2.3 on 2023-09-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0018_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField()),
                ('dateSent', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.article')),
            ],
        ),
    ]
