# Generated by Django 4.2.3 on 2023-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='dateSent',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sent',
            field=models.BooleanField(editable=False),
        ),
    ]
