# Generated by Django 4.2.3 on 2023-09-28 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_alter_letter_datesent_alter_letter_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='updated',
        ),
        migrations.AddField(
            model_name='letter',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=75),
            preserve_default=False,
        ),
    ]
