# Generated by Django 4.2.3 on 2024-01-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_alter_letter_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='article',
        ),
    ]
