# Generated by Django 4.2.3 on 2023-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='responded',
            new_name='responses',
        ),
        migrations.AddField(
            model_name='contact',
            name='recaptchaScore',
            field=models.FloatField(default=0.9, editable=False),
            preserve_default=False,
        ),
    ]
