# Generated by Django 4.2.3 on 2023-09-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_responded_contact_responses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='recaptchaScore',
        ),
    ]
